# Generated by Django 4.2.16 on 2026-02-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('university', models.CharField(choices=[('HARVARD', 'Harvard University'), ('MIT', 'MIT'), ('YALE', 'Yale University'), ('PRINCETON', 'Princeton University'), ('COLUMBIA', 'Columbia University'), ('CORNELL', 'Cornell University'), ('STANFORD', 'Stanford University'), ('PENN', 'University of Pennsylvania'), ('DARTMOUTH', 'Dartmouth College'), ('BROWN', 'Brown University')], max_length=50)),
                ('domain', models.CharField(choices=[('AI', 'Artificial Intelligence'), ('LAW', 'Law'), ('BIO', 'Biomedical'), ('ECE', 'Electronics & Communication'), ('CS', 'Computer Science'), ('BUSINESS', 'Business & Management'), ('ENV', 'Environmental Science'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('opportunity_type', models.CharField(choices=[('INTERNSHIP', 'Research Internship'), ('HACKATHON', 'Hackathon'), ('WORKSHOP', 'Workshop'), ('CONFERENCE', 'Conference'), ('SCHOLARSHIP', 'Scholarship'), ('FELLOWSHIP', 'Fellowship'), ('COMPETITION', 'Competition'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('description', models.TextField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('source_url', models.URLField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('stipend', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, default='Remote / On-campus', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Opportunities',
                'ordering': ['-scraped_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('opportunities_found', models.IntegerField(default=0)),
                ('new_opportunities', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='RUNNING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
            ],
        ),
    ]
