# Generated by Django 4.2.16 on 2026-02-22 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opportunities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('SUBMITTED', 'Submitted'), ('IN_REVIEW', 'Under Review'), ('SHORTLISTED', 'Shortlisted'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=20)),
                ('cover_letter', models.TextField(blank=True, help_text='Optional cover letter for this application')),
                ('resume_used', models.FileField(blank=True, null=True, upload_to='application_resumes/')),
                ('auto_submitted', models.BooleanField(default=False, help_text='Was this submitted via auto-fill?')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this application')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='opportunities.opportunity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('student', 'opportunity')},
            },
        ),
        migrations.CreateModel(
            name='AutoFillLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_url', models.URLField()),
                ('fields_detected', models.JSONField(default=list, help_text='List of form fields found')),
                ('fields_filled', models.JSONField(default=list, help_text='List of fields we successfully filled')),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
            ],
        ),
    ]
