# Generated by Django 4.2.16 on 2026-02-22 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_history', to='profiles.studentprofile')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('RESEARCH', 'Research Paper Published'), ('HACKATHON', 'Hackathon / Competition Win'), ('INTERNSHIP', 'Internship Completed'), ('CODING', 'Competitive Coding'), ('CONFERENCE', 'Conference Participation'), ('CERTIFICATION', 'Certification / Course'), ('PROJECT', 'Open Source / Project'), ('AWARD', 'Award / Recognition')], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('proof_url', models.URLField(blank=True, help_text='Link to certificate, paper, or result')),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='achievement_proofs/')),
                ('raw_score', models.FloatField(default=10.0, help_text='Raw score 0-100 for this achievement')),
                ('verified', models.BooleanField(default=False)),
                ('verified_by', models.CharField(blank=True, max_length=100)),
                ('achieved_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='profiles.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
